# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lite.ui'
#
# Created: Sun Dec 08 16:39:20 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(190, 140)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(190, 145))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(53, 53, 53))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/root/lite.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(53, 53, 53); color: rgb(200,200,200)"))
        MainWindow.setAnimated(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, -10, 191, 171))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.ask = QtGui.QLabel(self.groupBox)
        self.ask.setGeometry(QtCore.QRect(60, 20, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Open Sans Semibold"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ask.setFont(font)
        self.ask.setObjectName(_fromUtf8("ask"))
        self.askl = QtGui.QLabel(self.groupBox)
        self.askl.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.askl.setObjectName(_fromUtf8("askl"))
        self.bid = QtGui.QLabel(self.groupBox)
        self.bid.setGeometry(QtCore.QRect(60, 60, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Open Sans Semibold"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bid.setFont(font)
        self.bid.setText(_fromUtf8(""))
        self.bid.setObjectName(_fromUtf8("bid"))
        self.alertl = QtGui.QLabel(self.groupBox)
        self.alertl.setGeometry(QtCore.QRect(70, 110, 46, 20))
        self.alertl.setAlignment(QtCore.Qt.AlignCenter)
        self.alertl.setObjectName(_fromUtf8("alertl"))
        self.bidl = QtGui.QLabel(self.groupBox)
        self.bidl.setGeometry(QtCore.QRect(20, 70, 31, 21))
        self.bidl.setObjectName(_fromUtf8("bidl"))
        self.refresh = QtGui.QPushButton(self.groupBox)
        self.refresh.setGeometry(QtCore.QRect(0, 130, 31, 23))
        self.refresh.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/root/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh.setIcon(icon1)
        self.refresh.setIconSize(QtCore.QSize(35, 35))
        self.refresh.setFlat(True)
        self.refresh.setObjectName(_fromUtf8("refresh"))
        self.high = QtGui.QLineEdit(self.groupBox)
        self.high.setGeometry(QtCore.QRect(140, 110, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Open Sans"))
        font.setPointSize(10)
        self.high.setFont(font)
        self.high.setMaxLength(3)
        self.high.setFrame(True)
        self.high.setObjectName(_fromUtf8("high"))
        self.last = QtGui.QLabel(self.groupBox)
        self.last.setGeometry(QtCore.QRect(30, 130, 151, 20))
        self.last.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.last.setObjectName(_fromUtf8("last"))
        self.low = QtGui.QLineEdit(self.groupBox)
        self.low.setGeometry(QtCore.QRect(10, 110, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Open Sans"))
        font.setPointSize(10)
        self.low.setFont(font)
        self.low.setInputMask(_fromUtf8(""))
        self.low.setMaxLength(2)
        self.low.setObjectName(_fromUtf8("low"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "LiteCoinz", None))
        self.ask.setText(_translate("MainWindow", "Loading...", None))
        self.askl.setText(_translate("MainWindow", "Ask:", None))
        self.alertl.setText(_translate("MainWindow", "Alert", None))
        self.bidl.setText(_translate("MainWindow", "Bid:", None))
        self.high.setText(_translate("MainWindow", "30", None))
        self.last.setText(_translate("MainWindow", "Last Update: ", None))
        self.low.setText(_translate("MainWindow", "15", None))

import hello_rc
